export interface Product {
  id: string
  name: string
  tagline: string
  description: string
  logo: string
  url: string
  category: string
  tags: string[]
  launchDate: string
  buzzScore: number
  buzzTrend: 'rising' | 'stable' | 'falling'
  buzzBreakdown: {
    twitter: number
    reddit: number
    hackerNews: number
    news: number
  }
  videoUrl?: string
  screenshots: string[]
  rivals: string[]
  verified: boolean
  badges: ('responsive' | 'transparent-pricing' | 'active-development')[]
}

export const categories = [
  'All',
  'AI Tools',
  'Developer Tools',
  'Productivity',
  'Design',
  'Marketing',
  'Analytics',
  'Automation',
  'Finance',
] as const

export type Category = (typeof categories)[number]

export const products: Product[] = [
  {
    id: 'cursor',
    name: 'Cursor',
    tagline: 'The AI-first code editor',
    description: 'Cursor is a code editor built for programming with AI. It features AI-powered code completion, chat, and edit capabilities that understand your entire codebase.',
    logo: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=100&h=100&fit=crop',
    url: 'https://cursor.sh',
    category: 'Developer Tools',
    tags: ['AI', 'Code Editor', 'IDE', 'Programming'],
    launchDate: '2023-03-14',
    buzzScore: 892,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 340, reddit: 220, hackerNews: 180, news: 152 },
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    screenshots: [
      'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=800&h=450&fit=crop',
    ],
    rivals: ['windsurf', 'github-copilot', 'codeium'],
    verified: true,
    badges: ['responsive', 'active-development'],
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    tagline: 'AI-powered IDE by Codeium',
    description: 'Windsurf is a full IDE with deep AI integration, offering intelligent code suggestions, automated refactoring, and natural language to code capabilities.',
    logo: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=100&h=100&fit=crop',
    url: 'https://codeium.com/windsurf',
    category: 'Developer Tools',
    tags: ['AI', 'IDE', 'Code Editor', 'Codeium'],
    launchDate: '2024-11-01',
    buzzScore: 756,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 280, reddit: 190, hackerNews: 156, news: 130 },
    screenshots: [
      'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=800&h=450&fit=crop',
    ],
    rivals: ['cursor', 'github-copilot', 'codeium'],
    verified: true,
    badges: ['transparent-pricing', 'active-development'],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    tagline: 'Your AI pair programmer',
    description: 'GitHub Copilot uses AI to suggest code and entire functions in real-time, right from your editor. Powered by OpenAI Codex.',
    logo: 'https://images.unsplash.com/photo-1618401479427-c8ef9465fbe1?w=100&h=100&fit=crop',
    url: 'https://github.com/features/copilot',
    category: 'Developer Tools',
    tags: ['AI', 'GitHub', 'Code Completion', 'Microsoft'],
    launchDate: '2021-06-29',
    buzzScore: 945,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 380, reddit: 240, hackerNews: 195, news: 130 },
    screenshots: [
      'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&h=450&fit=crop',
    ],
    rivals: ['cursor', 'windsurf', 'codeium'],
    verified: true,
    badges: ['responsive', 'transparent-pricing'],
  },
  {
    id: 'codeium',
    name: 'Codeium',
    tagline: 'Free AI code completion',
    description: 'Codeium is a free AI-powered code completion tool that integrates with all major IDEs and supports over 70 programming languages.',
    logo: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=100&h=100&fit=crop',
    url: 'https://codeium.com',
    category: 'Developer Tools',
    tags: ['AI', 'Code Completion', 'Free', 'IDE Extension'],
    launchDate: '2022-10-01',
    buzzScore: 634,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 210, reddit: 180, hackerNews: 144, news: 100 },
    screenshots: [
      'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800&h=450&fit=crop',
    ],
    rivals: ['cursor', 'windsurf', 'github-copilot'],
    verified: true,
    badges: ['transparent-pricing'],
  },
  {
    id: 'v0',
    name: 'v0',
    tagline: 'Generate UI with AI',
    description: 'v0 by Vercel is a generative UI tool that creates React components from text descriptions. It uses AI to generate beautiful, functional UI code.',
    logo: 'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=100&h=100&fit=crop',
    url: 'https://v0.dev',
    category: 'AI Tools',
    tags: ['AI', 'UI Generation', 'React', 'Vercel'],
    launchDate: '2023-09-01',
    buzzScore: 823,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 320, reddit: 200, hackerNews: 175, news: 128 },
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    screenshots: [
      'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
    ],
    rivals: ['bolt', 'lovable', 'claude-artifacts'],
    verified: true,
    badges: ['responsive', 'active-development'],
  },
  {
    id: 'bolt',
    name: 'Bolt',
    tagline: 'Build full-stack apps instantly',
    description: 'Bolt.new lets you prompt, run, edit, and deploy full-stack web applications directly in your browser with AI assistance.',
    logo: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=100&h=100&fit=crop',
    url: 'https://bolt.new',
    category: 'AI Tools',
    tags: ['AI', 'Full-Stack', 'No-Code', 'Web Apps'],
    launchDate: '2024-09-01',
    buzzScore: 712,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 290, reddit: 175, hackerNews: 147, news: 100 },
    screenshots: [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
    ],
    rivals: ['v0', 'lovable', 'replit'],
    verified: true,
    badges: ['active-development'],
  },
  {
    id: 'lovable',
    name: 'Lovable',
    tagline: 'The AI full-stack engineer',
    description: 'Lovable is an AI-powered platform that helps you build production-ready applications with natural language prompts.',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=100&h=100&fit=crop',
    url: 'https://lovable.dev',
    category: 'AI Tools',
    tags: ['AI', 'Full-Stack', 'App Builder', 'No-Code'],
    launchDate: '2024-06-01',
    buzzScore: 589,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 230, reddit: 145, hackerNews: 124, news: 90 },
    screenshots: [
      'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&h=450&fit=crop',
    ],
    rivals: ['v0', 'bolt', 'replit'],
    verified: false,
    badges: [],
  },
  {
    id: 'notion',
    name: 'Notion',
    tagline: 'All-in-one workspace',
    description: 'Notion is an all-in-one workspace that combines notes, docs, wikis, and project management into a single, flexible tool.',
    logo: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=100&h=100&fit=crop',
    url: 'https://notion.so',
    category: 'Productivity',
    tags: ['Productivity', 'Notes', 'Wiki', 'Project Management'],
    launchDate: '2016-06-01',
    buzzScore: 876,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 350, reddit: 220, hackerNews: 170, news: 136 },
    screenshots: [
      'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=450&fit=crop',
    ],
    rivals: ['obsidian', 'coda', 'roam'],
    verified: true,
    badges: ['responsive', 'transparent-pricing', 'active-development'],
  },
  {
    id: 'obsidian',
    name: 'Obsidian',
    tagline: 'A second brain, for you, forever',
    description: 'Obsidian is a powerful knowledge base that works on top of a local folder of plain text Markdown files.',
    logo: 'https://images.unsplash.com/photo-1633409361618-c73427e4e206?w=100&h=100&fit=crop',
    url: 'https://obsidian.md',
    category: 'Productivity',
    tags: ['Notes', 'Markdown', 'Knowledge Base', 'PKM'],
    launchDate: '2020-03-01',
    buzzScore: 745,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 280, reddit: 210, hackerNews: 155, news: 100 },
    screenshots: [
      'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=450&fit=crop',
    ],
    rivals: ['notion', 'roam', 'logseq'],
    verified: true,
    badges: ['transparent-pricing'],
  },
  {
    id: 'linear',
    name: 'Linear',
    tagline: 'The issue tracking tool you will enjoy using',
    description: 'Linear is a better way to build software. Meet the system designed for modern software development. Streamline issues, projects, and product roadmaps.',
    logo: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=100&h=100&fit=crop',
    url: 'https://linear.app',
    category: 'Developer Tools',
    tags: ['Project Management', 'Issue Tracking', 'Software Development'],
    launchDate: '2019-12-01',
    buzzScore: 812,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 310, reddit: 200, hackerNews: 182, news: 120 },
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    screenshots: [
      'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=450&fit=crop',
    ],
    rivals: ['jira', 'asana', 'shortcut'],
    verified: true,
    badges: ['responsive', 'active-development'],
  },
  {
    id: 'figma',
    name: 'Figma',
    tagline: 'The collaborative interface design tool',
    description: 'Figma is a cloud-based design tool that allows teams to collaborate in real-time on interface design, prototyping, and design systems.',
    logo: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=100&h=100&fit=crop',
    url: 'https://figma.com',
    category: 'Design',
    tags: ['Design', 'UI/UX', 'Collaboration', 'Prototyping'],
    launchDate: '2016-09-01',
    buzzScore: 934,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 370, reddit: 230, hackerNews: 194, news: 140 },
    screenshots: [
      'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1558655146-d09347e92766?w=800&h=450&fit=crop',
    ],
    rivals: ['sketch', 'adobe-xd', 'framer'],
    verified: true,
    badges: ['responsive', 'transparent-pricing', 'active-development'],
  },
  {
    id: 'framer',
    name: 'Framer',
    tagline: 'Design and publish stunning sites',
    description: 'Framer is a powerful web design tool that allows you to create responsive, interactive websites without writing code.',
    logo: 'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=100&h=100&fit=crop',
    url: 'https://framer.com',
    category: 'Design',
    tags: ['Web Design', 'No-Code', 'Publishing', 'Interactive'],
    launchDate: '2018-01-01',
    buzzScore: 678,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 260, reddit: 170, hackerNews: 148, news: 100 },
    screenshots: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=450&fit=crop',
    ],
    rivals: ['figma', 'webflow', 'squarespace'],
    verified: true,
    badges: ['active-development'],
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    tagline: 'AI image generation',
    description: 'Midjourney is an AI-powered tool that generates images from natural language descriptions, known for its artistic and high-quality outputs.',
    logo: 'https://images.unsplash.com/photo-1686191128892-3b37add4d6bd?w=100&h=100&fit=crop',
    url: 'https://midjourney.com',
    category: 'AI Tools',
    tags: ['AI', 'Image Generation', 'Art', 'Creative'],
    launchDate: '2022-07-01',
    buzzScore: 967,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 400, reddit: 250, hackerNews: 167, news: 150 },
    screenshots: [
      'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1684493735806-d86ac60f4417?w=800&h=450&fit=crop',
    ],
    rivals: ['dall-e', 'stable-diffusion', 'leonardo'],
    verified: true,
    badges: ['active-development'],
  },
  {
    id: 'dall-e',
    name: 'DALL-E',
    tagline: 'Create realistic images from text',
    description: 'DALL-E by OpenAI creates realistic images and art from natural language descriptions. It can combine concepts, attributes, and styles.',
    logo: 'https://images.unsplash.com/photo-1676299081847-824916de030a?w=100&h=100&fit=crop',
    url: 'https://openai.com/dall-e',
    category: 'AI Tools',
    tags: ['AI', 'Image Generation', 'OpenAI', 'Creative'],
    launchDate: '2021-01-01',
    buzzScore: 856,
    buzzTrend: 'falling',
    buzzBreakdown: { twitter: 340, reddit: 210, hackerNews: 176, news: 130 },
    screenshots: [
      'https://images.unsplash.com/photo-1679083216051-aa510a1a2c0e?w=800&h=450&fit=crop',
    ],
    rivals: ['midjourney', 'stable-diffusion', 'imagen'],
    verified: true,
    badges: ['responsive'],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    tagline: 'Develop. Preview. Ship.',
    description: 'Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration.',
    logo: 'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=100&h=100&fit=crop',
    url: 'https://vercel.com',
    category: 'Developer Tools',
    tags: ['Hosting', 'Deployment', 'Frontend', 'Next.js'],
    launchDate: '2015-11-01',
    buzzScore: 889,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 350, reddit: 220, hackerNews: 189, news: 130 },
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
    ],
    rivals: ['netlify', 'cloudflare-pages', 'railway'],
    verified: true,
    badges: ['responsive', 'transparent-pricing', 'active-development'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    tagline: 'The open source Firebase alternative',
    description: 'Supabase is an open source Firebase alternative providing all the backend features you need to build a product: database, auth, storage, and more.',
    logo: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=100&h=100&fit=crop',
    url: 'https://supabase.com',
    category: 'Developer Tools',
    tags: ['Database', 'Auth', 'Backend', 'PostgreSQL'],
    launchDate: '2020-01-01',
    buzzScore: 834,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 320, reddit: 210, hackerNews: 184, news: 120 },
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    screenshots: [
      'https://images.unsplash.com/photo-1489875347897-49f64b51c1f8?w=800&h=450&fit=crop',
    ],
    rivals: ['firebase', 'planetscale', 'neon'],
    verified: true,
    badges: ['responsive', 'transparent-pricing', 'active-development'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    tagline: 'Financial infrastructure for the internet',
    description: 'Stripe is a technology company that builds economic infrastructure for the internet. Millions of companies use Stripe to accept payments and manage their businesses online.',
    logo: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=100&h=100&fit=crop',
    url: 'https://stripe.com',
    category: 'Finance',
    tags: ['Payments', 'Finance', 'API', 'E-commerce'],
    launchDate: '2011-09-01',
    buzzScore: 912,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 360, reddit: 225, hackerNews: 192, news: 135 },
    screenshots: [
      'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=450&fit=crop',
    ],
    rivals: ['paddle', 'lemonsqueezy', 'paypal'],
    verified: true,
    badges: ['responsive', 'transparent-pricing'],
  },
  {
    id: 'claude',
    name: 'Claude',
    tagline: 'AI assistant by Anthropic',
    description: 'Claude is an AI assistant created by Anthropic to be helpful, harmless, and honest. It excels at analysis, coding, math, and creative tasks.',
    logo: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop',
    url: 'https://claude.ai',
    category: 'AI Tools',
    tags: ['AI', 'Assistant', 'LLM', 'Anthropic'],
    launchDate: '2023-03-01',
    buzzScore: 978,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 410, reddit: 260, hackerNews: 178, news: 130 },
    screenshots: [
      'https://images.unsplash.com/photo-1676299081847-824916de030a?w=800&h=450&fit=crop',
    ],
    rivals: ['chatgpt', 'gemini', 'perplexity'],
    verified: true,
    badges: ['responsive', 'active-development'],
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'AI language model by OpenAI',
    description: 'ChatGPT is an AI-powered language model developed by OpenAI, capable of generating human-like text based on context and past conversations.',
    logo: 'https://images.unsplash.com/photo-1676299081847-824916de030a?w=100&h=100&fit=crop',
    url: 'https://chat.openai.com',
    category: 'AI Tools',
    tags: ['AI', 'LLM', 'OpenAI', 'Chat'],
    launchDate: '2022-11-30',
    buzzScore: 998,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 420, reddit: 270, hackerNews: 168, news: 140 },
    screenshots: [
      'https://images.unsplash.com/photo-1675557009483-e74ac53a8fb1?w=800&h=450&fit=crop',
    ],
    rivals: ['claude', 'gemini', 'perplexity'],
    verified: true,
    badges: ['responsive'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    tagline: 'AI-powered search engine',
    description: 'Perplexity is an AI-powered search engine that provides direct answers to questions with cited sources, combining search and AI chat.',
    logo: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=100&h=100&fit=crop',
    url: 'https://perplexity.ai',
    category: 'AI Tools',
    tags: ['AI', 'Search', 'Research', 'LLM'],
    launchDate: '2022-12-01',
    buzzScore: 867,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 350, reddit: 220, hackerNews: 167, news: 130 },
    screenshots: [
      'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=800&h=450&fit=crop',
    ],
    rivals: ['chatgpt', 'claude', 'you-com'],
    verified: true,
    badges: ['active-development'],
  },
  {
    id: 'raycast',
    name: 'Raycast',
    tagline: 'Your shortcut to everything',
    description: 'Raycast is a blazingly fast, totally extendable launcher for Mac that lets you complete tasks, calculate, share common links, and much more.',
    logo: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=100&h=100&fit=crop',
    url: 'https://raycast.com',
    category: 'Productivity',
    tags: ['Productivity', 'Mac', 'Launcher', 'Automation'],
    launchDate: '2020-08-01',
    buzzScore: 723,
    buzzTrend: 'stable',
    buzzBreakdown: { twitter: 280, reddit: 185, hackerNews: 158, news: 100 },
    screenshots: [
      'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=450&fit=crop',
    ],
    rivals: ['alfred', 'spotlight', 'launchbar'],
    verified: true,
    badges: ['responsive', 'active-development'],
  },
  {
    id: 'arc',
    name: 'Arc Browser',
    tagline: 'A better way to use the internet',
    description: 'Arc is a browser that reimagines the web experience with spaces, profiles, and a focus on productivity and organization.',
    logo: 'https://images.unsplash.com/photo-1585814240392-e35d91ebe5fa?w=100&h=100&fit=crop',
    url: 'https://arc.net',
    category: 'Productivity',
    tags: ['Browser', 'Productivity', 'Mac', 'Windows'],
    launchDate: '2022-04-01',
    buzzScore: 689,
    buzzTrend: 'falling',
    buzzBreakdown: { twitter: 260, reddit: 175, hackerNews: 154, news: 100 },
    screenshots: [
      'https://images.unsplash.com/photo-1481487196290-c152afe65b55?w=800&h=450&fit=crop',
    ],
    rivals: ['chrome', 'safari', 'brave'],
    verified: true,
    badges: ['active-development'],
  },
  {
    id: 'posthog',
    name: 'PostHog',
    tagline: 'Open source product analytics',
    description: 'PostHog is an all-in-one platform for product analytics, feature flags, session recordings, A/B testing, and surveys - all open source.',
    logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop',
    url: 'https://posthog.com',
    category: 'Analytics',
    tags: ['Analytics', 'Open Source', 'Product', 'Feature Flags'],
    launchDate: '2020-02-01',
    buzzScore: 756,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 290, reddit: 195, hackerNews: 171, news: 100 },
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
    ],
    rivals: ['mixpanel', 'amplitude', 'heap'],
    verified: true,
    badges: ['responsive', 'transparent-pricing', 'active-development'],
  },
  {
    id: 'resend',
    name: 'Resend',
    tagline: 'Email for developers',
    description: 'Resend is the email API for developers. Build, test, and send transactional emails at scale with a modern, developer-friendly platform.',
    logo: 'https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=100&h=100&fit=crop',
    url: 'https://resend.com',
    category: 'Developer Tools',
    tags: ['Email', 'API', 'Transactional', 'Developer Tools'],
    launchDate: '2023-01-01',
    buzzScore: 634,
    buzzTrend: 'rising',
    buzzBreakdown: { twitter: 240, reddit: 160, hackerNews: 144, news: 90 },
    screenshots: [
      'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?w=800&h=450&fit=crop',
    ],
    rivals: ['sendgrid', 'postmark', 'mailgun'],
    verified: true,
    badges: ['responsive', 'transparent-pricing', 'active-development'],
  },
]

export function getProduct(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getRivals(product: Product): Product[] {
  return product.rivals
    .map((id) => getProduct(id))
    .filter((p): p is Product => p !== undefined)
}

export function getProductsByCategory(category: Category): Product[] {
  if (category === 'All') return products
  return products.filter((p) => p.category === category)
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.tagline.toLowerCase().includes(lowerQuery) ||
      p.tags.some((t) => t.toLowerCase().includes(lowerQuery))
  )
}
